### ISSUE TITLE
Call command bug

### ISSUE THREAD

**Issue by stastnypremysl** [utkuufuk/weekplot#1]
When I call  `python3 weekplot.py ./events.yml`, there is no generated plot in the folder. Shoudn't it be equivalent to `python3 weekplot.py events.yml`?

**Comment by utkuufuk** [comment]
@stastnypremysl You're right, the two calls should be equivalent. 

It should be fixed with PR https://github.com/utkuufuk/weekplot/pull/3. Could you pull the [branch]( https://github.com/utkuufuk/weekplot/tree/pathfix) and let me know if it works for you?

**Comment by stastnypremysl** [comment]
Yes, it works for me. Thank you.
